# Generated by Django 4.2 on 2023-04-16 23:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0002_rename_puntos_student_points'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_de_lista', models.IntegerField()),
                ('id_student', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_de_grupo', models.IntegerField(unique=True)),
                ('id_grupo', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profesor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('id_profesor', models.CharField(max_length=255, unique=True)),
                ('nombre', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('id_grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontend.grupo')),
            ],
        ),
        migrations.CreateModel(
            name='Pregunta',
            fields=[
                ('id_pregunta', models.IntegerField(primary_key=True, serialize=False)),
                ('pregunta', models.TextField()),
                ('respuestas_correcta', models.IntegerField()),
                ('respuesta_alumno', models.IntegerField()),
                ('resultado', models.BooleanField()),
                ('nivel', models.CharField(max_length=255)),
                ('dificultad', models.IntegerField()),
                ('fecha', models.DateTimeField()),
                ('tiempo_asignado', models.IntegerField()),
                ('id_student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontend.estudiante')),
            ],
        ),
        migrations.AddField(
            model_name='estudiante',
            name='id_grupo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontend.grupo'),
        ),
    ]
