# Generated by Django 4.2 on 2023-04-16 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0003_estudiante_grupo_profesor_pregunta_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profesor',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='profesor',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profesor',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.AlterField(
            model_name='profesor',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='profesor',
            name='id_grupo',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='profesor',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
    ]
