# Generated by Django 4.2 on 2023-04-16 23:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0004_profesor_is_active_profesor_is_staff_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profesor',
            name='id_grupo',
        ),
    ]
