# Generated by Django 4.2 on 2023-04-17 00:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0006_remove_profesor_id_profesor'),
    ]

    operations = [
        migrations.AddField(
            model_name='profesor',
            name='grupo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='frontend.grupo'),
        ),
    ]
