# Generated by Django 4.2 on 2023-04-17 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0007_profesor_grupo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profesor',
            name='last_login',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
    ]
