# Generated by Django 4.2 on 2023-04-18 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0009_remove_estudiante_id_student_delete_pregunta'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pregunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grupo', models.CharField(max_length=200)),
                ('pregunta', models.CharField(max_length=200)),
                ('respuestas_correcta', models.IntegerField()),
                ('respuesta_alumno', models.IntegerField()),
                ('resultado', models.BooleanField()),
                ('nivel', models.CharField(max_length=255)),
                ('dificultad', models.IntegerField()),
                ('fecha', models.DateTimeField()),
                ('tiempo_asignado', models.IntegerField()),
            ],
        ),
    ]
