# Generated by Django 4.2 on 2023-04-18 04:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0010_pregunta'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pregunta',
        ),
    ]
