# Generated by Django 4.2 on 2023-04-19 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0013_rename_respuesta_alumno_pregunta_respuesta_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pregunta',
            name='respuesta_alumno',
            field=models.IntegerField(default=4),
            preserve_default=False,
        ),
    ]
