# Generated by Django 4.2 on 2023-04-20 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0014_pregunta_respuesta_alumno'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estudiante',
            name='id_grupo',
        ),
        migrations.AddField(
            model_name='estudiante',
            name='grupo',
            field=models.CharField(default=1, max_length=1),
            preserve_default=False,
        ),
    ]
